name: Check Backend Unit Test

on: push

jobs:
  test:
    name: Testing TC
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: Install all dependencies
        run: go get
        working-directory: ./src/backend
      - name: Running CI
        run: go test -v ./...
        working-directory: ./src/backend
